version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpass
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  app:
    # For building via local code use below and comment out the image field
    # build: .
    image: ananthkamath/twitter-clone:v1
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
